apiVersion: v1
kind: Service
metadata:
  labels:
    app: parksmap
  name: parksmap
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: parksmap
